name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Create a Release
      uses: marvinpinto/action-automatic-releases@latest      
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ github.ref }}
        title: Release ${{ github.ref }}
        draft: false
        prerelease: false