name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Create a Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        # automatic_release_tag: ${{ github.ref }}
        title: Release ${{ github.ref }}
        draft: false
        prerelease: false