name: Get release tag

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  get_tags:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Get tag from ref_name
        run: |
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_ENV
      -
        name: Print environment variables
        run: |
          echo $GITHUB_ENV

