name: Get release tag

on:
  release:
    types: [published]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Get GitHub release tags
        run: |
          echo "REF_NAME"=${{ github.ref_name }} >> $GITHUB_ENV
          echo "REF"=${{ github.ref }} >> $GITHUB_ENV

  print_tags:
    needs: get_tags
    runs-on: ubuntu-latest
    steps:
      -
        name: Print environment variables
        run: |
          echo $GITHUB_ENV
